export interface ITest {
	IndexInt: number,
	_Float: number,
	stringArr: string[],
	floatArr2: number[][],
	string: string,
	intArr: number[],
	anyArr2: any[][],
	_Int: number,
	anyArr: any[],
	M: any,
	M2: any,
	floatArr: number[],
	intArr2: number[][],
	stringArr2: string[][],
}